module.exports = {
  users: require("./users"),
  admin: require("./admin"),
  appregistration: require("./appregistration"),
  usersSession: require("./user_sessions"),
  verification: require("./verification"),
  agencies: require("./agencies"),
  follow: require("./follow"),
  membership: require("./membership"),
  recharge: require("./recharge"),
  charges: require("./charges"),
  reports: require("./reports"),
  settlements: require("./settlements"),
  payments: require("./payments"),
};
